include:
  - my-apps.yml
  - services.yml

services:

  ddclient-fruzyna:
    image: ${LSIO_REGISTRY}/ddclient
    container_name: ddclient-fruzyna
    environment:
      - PUID=${USER_ID}
      - PGID=${USER_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/ddclient/fruzyna:/config:Z
    restart: always

  ddclient-wildrank:
    image: ${LSIO_REGISTRY}/ddclient
    container_name: ddclient-wildrank
    environment:
      - PUID=${USER_ID}
      - PGID=${USER_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/ddclient/wildrank:/config:Z
    restart: always

  ddclient-wildzone:
    image: ${LSIO_REGISTRY}/ddclient
    container_name: ddclient-wildzone
    environment:
      - PUID=${USER_ID}
      - PGID=${USER_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/ddclient/wildzone:/config:Z
    restart: always

  ddclient-wildstang:
    image: ${LSIO_REGISTRY}/ddclient
    container_name: ddclient-wildstang
    environment:
      - PUID=${USER_ID}
      - PGID=${USER_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/ddclient/wildstang:/config:Z
    restart: always

  reverse-proxy:
    image: ${LSIO_REGISTRY}/swag
    container_name: reverse-proxy
    env_file: secrets/lets-encrypt.env
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${USER_ID}
      - PGID=${USER_ID}
      - TZ=${TIMEZONE}
      - VALIDATION=http
    volumes:
      - ./nginx:/config/nginx:Z
      - ./pages:/config/pages:Z
      - ${DATA_DIR}/nginx-logs:/config/log/nginx:Z
      - ${DATA_DIR}/fileserver:/config/fileserver:Z
      - ${CONFIG_DIR}/letsencrypt:/config/etc/letsencrypt:Z
    ports:
      - 443:443
      - 80:80
    restart: always

  cups:
    build: ./cups
    container_name: cups
    privileged: true
    volumes:
      - ${CONFIG_DIR}/cups:/etc/cups:Z
      - /var/run/dbus:/var/run/dbus:Z,ro
      - /dev/bus/usb/001:/dev/bus/usb/001:Z
    ports:
      - 631:631
    restart: always
