services:

  metra:
    image: ${MY_REGISTRY}/metra
    container_name: metra
    volumes:
      - ${CONFIG_DIR}/metra:/config:Z
    ports:
      - ${METRA_PORT}:80
    restart: always

  personal-site:
    image: ${MY_REGISTRY}/site
    container_name: personal-site
    user: ${USER_ID}:${USER_ID}
    userns_mode: keep-id
    volumes:
      - ${CONFIG_DIR}/personal-site:/app/config:Z
    ports:
      - ${PERSONAL_PORT}:8000
    networks:
      - personal
    restart: always

  races:
    image: ${MY_REGISTRY}/races
    container_name: races
    volumes:
      - ${CONFIG_DIR}/races:/app/config:Z
    ports:
      - ${RACES_PORT}:8000
    restart: always

  wildrank:
    image: ${WS_REGISTRY}/wildrank:5.2.0
    container_name: wildrank
    env_file: secrets/wildrank.env
    environment:
      - WR_WORKERS=10
    volumes:
      - ${CONFIG_DIR}/wildrank:/config:Z
    ports:
      - ${WILDRANK_PORT}:80
    networks:
      - wildrank
    restart: always

  wildrank-test:
    image: ${WS_REGISTRY}/wildrank:5.2.0
    container_name: wildrank-test
    env_file: secrets/wildrank.env
    environment:
      - WR_WORKERS=5
    volumes:
      - ${CONFIG_DIR}/wildrank-test:/config:Z
    ports:
      - ${WILDRANK_TEST_PORT}:80
    networks:
      - wildrank
    restart: always

  wildzone:
    image: ${WS_REGISTRY}/wildzone:0.5
    container_name: wildzone
    environment:
      - WZ_WORKERS=10
    volumes:
      - ${CONFIG_DIR}/wildzone:/app/config:Z
    ports:
      - ${WILDZONE_PORT}:80
    restart: always

networks:

  personal:
    internal: true

  wildrank:
    internal: true
